version: '3'
services:
  fluentd:
    container_name: fluentd
    image: fluentd
    user: root
    volumes:
    - /var/lib/docker/containers:/fluentd/log/containers
    - ./conf:/fluentd/etc/
    - ./logs:/output/
    # logging:
    #   driver: "local"
    
    # command: [ /bin/sh , -c , "sudo chmod 777 /var/lib/docker/containers"]